# Generated by Django 4.2.20 on 2025-05-05 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='contact_address',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='on_trial',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='paid_until',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='subscription_plan',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='website',
        ),
    ]
