services:
  web:
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    command: /entrypoint.sh
    volumes:
      - ../../:/app
      - static_volume:/app/backend/staticfiles
      - media_volume:/app/backend/mediafiles
    expose:
      - 8000
    environment:
      - DJANGO_ENV=production
      - DJANGO_SETTINGS_MODULE=core.settings.production
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web

  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=django_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

  celery_worker:
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    command: celery -A core worker -l info
    volumes:
      - ../../:/app
    environment:
      - DJANGO_ENV=production
      - DJANGO_SETTINGS_MODULE=core.settings.production
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      web:
        condition: service_started

  celery_beat:
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    command: celery -A core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ../../:/app
    environment:
      - DJANGO_ENV=production
      - DJANGO_SETTINGS_MODULE=core.settings.production
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      web:
        condition: service_started

  flower:
    build:
      context: ../../
      dockerfile: docker/prod/Dockerfile
    command: celery -A core flower
    ports:
      - "5555:5555"
    volumes:
      - ../../:/app
    environment:
      - DJANGO_ENV=production
      - DJANGO_SETTINGS_MODULE=core.settings.production
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      web:
        condition: service_started

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume: